services:
  app:
    build: .
    env_file:
      - .env.private
      - .env
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: