services:
  app:
    build: .
    env_file:
      - .env.private
      - .env
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - .env
      - .env.private
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: